### ISSUE TITLE
"Country_Name"

### ISSUE THREAD

**Issue by shortsguy** [zoharsf/Coronavirus_Tracker#2]
"Country_Name" does not pull the country name in or is it a variable that needs to be manually changed?
Found around line 108.

**Comment by zoharsf** [comment]
There are two instances of `COUNTRY_NAME` in the code, one in line 37 and one in line 98.
Both need to be replaced manually with the desired country name as described in the readme [here](https://github.com/zoharsf/Coronavirus_Tracker#code-configuration)
